### ISSUE TITLE
Classes derived from BlockSlab call incorrect constructor

### ISSUE THREAD

**Issue by bigbadwolf88888** [localtoast9001/forge-mods#1]
Please ignore. I was looking at the wrong branch.

**Comment by localtoast9001** [comment]
Thanks for the compliments. I'm working on different roofing blocks right now. I feel like I need more stuff before I release the mod.

**Comment by bigbadwolf88888** [comment]
I'm pouring through your code. Great quality stuff.  

I'd say your mod is useful as-is and adds a lot of great building potential. Plus, there are currently limited mods out for 1.8 so I'm sure the community would appreciate it. 

I'm attempting to build dirt, gravel, and sand slabs. The main goal is to make road and path construction in MC more natural looking and improve travel speeds. If I manage to get it working, i'll share it.  If I develop any degree of proficiency at this, I'll contribute.

**Comment by localtoast9001** [comment]
Awesome idea for your mod. Based on your advice, I think I'll release mine after I finish this thatched roofing block I'm currently working on. Best of luck on your mod. I hope to play it soon.
